version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/public_html/operation-ignition
script:
  cd /home/ec2-user/public_html/operation-ignition
  tmux kill-session -t ignite
  tmux new -s ignite
  npm start